version: 2
jobs:
  build:
    machine:
      python:
        version: 3.5.2
    steps:
      - run: pip install pyyaml jsonschema pysha3
  sani:
    machine:
        python:
          version: 3.5.2
    steps:
      - checkout
      - run: pyenv global 3.5.2
      - run: make sani
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - sani