version: 2
jobs:
  build:
    machine:
      python:
        version: 3.6.1
    steps:
      - run: pip install pyyaml jsonschema pysha3
  sani:
    machine: true
    steps:
      - checkout
      - run: alias python3=python
      - run: make sani
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - sani